#!/bin/bash

url_video="$1"

nome_do_video=$(youtube-dl --get-filename $url_video | cut -d "." -f1)

dados=$(youtube-dl -F "$url_video")
dados_do_audio=$(echo "$dados" | grep "audio only")
dados_do_video=$(echo "$dados" | grep -v "audio only" | grep -E '[0-9]{0,9}k')

##################################################

qualidade_1=0
while read -r dado_audio
do
    qualidade_2=$(echo "$dado_audio" | grep "audio only" | awk '{print $6}' | grep -Eo '[0-9]{0,9}k')
    if [ "${qualidade_2/k/}" -gt "$qualidade_1" ]; then
        qualidade_1=${qualidade_2/k/}
        melhor_audio=$dado_audio
        id_audio=$(echo "$dado_audio" | awk '{print $1}')
    fi
done <<< $dados_do_audio

echo "Melhor áudio: $id_audio"
echo "$melhor_audio"

##################################################

qualidade_1=0
while read -r dado_video
do
    qualidade_2=$(echo "$dado_video" | grep -v "audio only" | grep -E '[0-9]{0,9}k' | awk '{print $5}' | grep -Eo '[0-9]{0,9}k')
    if [ "${qualidade_2/k/}" -gt "$qualidade_1" ]; then
        qualidade_1=${qualidade_2/k/}
        melhor_video=$dado_video
        id_video=$(echo "$dado_video" | awk '{print $1}')
    fi  
done <<< $dados_do_video

echo "Melhor vídeo: $id_video"
echo "$melhor_video"

comando=$(echo "youtube-dl -f "$id_video"+"$id_audio" "$url_video"")

echo "Baixando com o comando: \"$comando\""
bash -c "$comando"

echo "Reproduzindo com o VLC..."
arquivo_de_video=$(ls -1 | grep "$nome_do_video")

vlc "$arquivo_de_video"
