#!/bin/bash

echo "Transmitindo para a porta 8080."
vlc -v screen:// --screen-fps=30 --input-slave=pulse://$(pacmd list-sources |grep "analog-stereo.monitor" | cut -f2 -d ":" |cut -f2 -d " " |sed 's/\(.\{1\}\)//' |sed s'/.$//') --sout '#transcode{vcodec=h264,vb=5000,scale=Automático,height=720px}:rtp{sdp=rtsp://:8554/teste}' --sout-all --sout-keep
