#!/bin/bash

ip=$(ip addr show | grep -o "inet [0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" | grep -o "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*")
echo "Script para a transmissão do áudio interno através do cvlc via HTTP."
read -p "Digite a porta: " PORTA

FONTE=$(pacmd list-sources |grep "analog-stereo.monitor" | cut -f2 -d ":" |cut -f2 -d " " |sed 's/\(.\{1\}\)//' |sed s'/.$//')

#Transmite para http://seu-ip:$PORTA
echo "Transmitindo usando o dispositivo $FONTE no endereço http://$ipi:$porta/"
cvlc -v pulse://$FONTE --sout '#transcode{vcodec=none,acodec=mp4a,ab=320,channels=2,samplerate=44100}:http{mux=ogg,dst=:$porta/}' :no-sout-all :sout-keep
