#!/bin/bash

PASTA=$1
PORTA=$2

cvlc -v dvdsimple://$PASTA --sout '#transcode{vcodec=h264,vb=5000,vfilter=deinterlace,scale=Automático,acodec=mp3,ab=320,channels=2,samplerate=44100}:http{mux=ts,dst=:$PORTA/}' :no-sout-all :sout-keep
