#!/bin/bash

FONTE=$(pacmd list-sources |grep "analog-stereo.monitor" | cut -f2 -d ":" |cut -f2 -d " " |sed 's/\(.\{1\}\)//' |sed s'/.$//')
porta=$1

if [ -z "${1}" ]; then
    echo "Falta especificar a porta!!"
    
else
    #Transmite para http://seu-ip:8080
    cvlc -v pulse://$FONTE --sout '#transcode{vcodec=none,acodec=mp4a,ab=320,channels=2,samplerate=44100}:http{mux=ogg,dst=:$porta/}' :no-sout-all :sout-keep

fi
