#!/bin/bash

vlc -v --sout '#transcode{vcodec=h264,vb=5000,vfilter=deinterlace,fps=30,scale=Automático,height=720,acodec=mp3,ab=320,channels=2,samplerate=44100}:duplicate{dst=http{mux=ts,dst=:8080/},dst=display}' --sout-all --sout-keep
