#!/bin/bash

sink=$(pacmd list sinks |grep aovivo)

if [ -z ${sink} ]; then
    pacmd load-module module-null-sink sink_name=aovivo
fi
ffplay -f lavfi -i "amovie=aovivo.monitor:f=pulse, asplit [a][out1]; [a] showspectrum=mode=separate:color=rainbow:slide=1:scale=sqrt:s=1020x1080 [out0]"
