#!/bin/bash

url_video="$1"
aplicativo='/usr/bin/yt-dlp'

nome_do_video=$($aplicativo --get-filename $url_video | cut -d "." -f1)

dados=$($aplicativo -F "$url_video")
dados_do_audio=$(echo "$dados" | grep "audio only")
dados_do_video=$(echo "$dados" | grep -v "audio only" | grep -E '[0-9]{0,9}k')

##################################################

qualidade_1=0
while read -r dado_audio
do
    qualidade_2=$(echo "$dado_audio" | grep "audio only" | grep -oE '[0-9]{0,9}k' | head -n 1)
    qualidade_2=${qualidade_2//[^0-9]/}

    if [[ -n "${qualidade_2}" && "${qualidade_2}" -gt "$qualidade_1" ]]; then
        qualidade_1=${qualidade_2}
        melhor_audio=$dado_audio
        id_audio=$(echo "$dado_audio" | awk '{print $1}')
    fi
done <<< $dados_do_audio

echo "Melhor áudio: $id_audio"
echo "$melhor_audio"
echo ""

##################################################

# Selecionando a maior resolução
maior_resulucao=$(echo "$dados_do_video" | grep -E '[0-9]+x[0-9]+' | awk '{split($3, a, "x"); print a[1]*a[2], $3}' | sort -nr | head -n 1 | awk '{print $2}')

# Selecionando a maior taxa de bits
qualidade_1=0
while read -r dado_video
do
    qualidade_2=$(echo "$dado_video" | grep -v "audio only" | grep -oE '[0-9]{0,9}k' | head -n 1)
    qualidade_2=${qualidade_2//[^0-9]/}

    if [[ -n "${qualidade_2}" && "${qualidade_2}" -gt "$qualidade_1" ]]; then
        qualidade_1=${qualidade_2}
        melhor_video=$dado_video
        id_video=$(echo "$dado_video" | awk '{print $1}')
    fi  
done <<< $(echo "$dados_do_video" | grep "$maior_resulucao")

echo "Melhor vídeo: $id_video"
echo "$melhor_video"
echo ""

##################################################

# Montando o comando de download
if [[ -n "$id_audio" ]]; then
    # Se há áudio separado, combina vídeo + áudio
    comando="$aplicativo -f \"$id_video+$id_audio\" \"$url_video\""
else
    # Se não há áudio separado, usa apenas o vídeo (que pode conter áudio embutido)
    comando="$aplicativo -f \"$id_video\" \"$url_video\""
fi

echo "Baixando com o comando: $comando"
bash -c "$comando"