#!/bin/bash

# Obter o certificado de um servidor

dominio="$1"
servidor="$2"

echo | openssl s_client -showcerts -servername $dominio -connect $servidor:443 2>/dev/null | openssl x509 -inform pem -noout -text
