#!/bin/bash

if [ "$EUID" -ne 0 ]; then
    echo "Por favor, execute:"
    echo "sudo $0"
    exit
fi

criar_esquema_chameleon_breeze_dark(){
    printf '%s\n'                          \
        '[ColorEffects:Disabled]'          \
        'ChangeSelectionColor='            \
        'Color=56,56,56'                   \
        'ColorAmount=0'                    \
        'ColorEffect=0'                    \
        'ContrastAmount=0.65'              \
        'ContrastEffect=1'                 \
        'Enable='                          \
        'IntensityAmount=0.1'              \
        'IntensityEffect=2'                \
        ''                                 \
        '[ColorEffects:Inactive]'          \
        'ChangeSelectionColor=true'        \
        'Color=112,111,110'                \
        'ColorAmount=0.025'                \
        'ColorEffect=2'                    \
        'ContrastAmount=0.1'               \
        'ContrastEffect=2'                 \
        'Enable=false'                     \
        'IntensityAmount=0'                \
        'IntensityEffect=0'                \
        ''                                 \
        '[Colors:Button]'                  \
        'BackgroundAlternate=14,131,113'   \
        'BackgroundNormal=49,54,59'        \
        'DecorationFocus=0,164,137'        \
        'DecorationHover=0,164,137'        \
        'ForegroundActive=0,164,137'       \
        'ForegroundInactive=161,169,177'   \
        'ForegroundLink=0,164,137'         \
        'ForegroundNegative=218,68,83'     \
        'ForegroundNeutral=246,116,0'      \
        'ForegroundNormal=252,252,252'     \
        'ForegroundPositive=39,174,96'     \
        'ForegroundVisited=155,89,182'     \
        ''                                 \
        '[Colors:Complementary]'           \
        'BackgroundAlternate=30,87,116'    \
        'BackgroundNormal=42,46,50'        \
        'DecorationFocus=0,164,137'        \
        'DecorationHover=0,164,137'        \
        'ForegroundActive=0,164,137'       \
        'ForegroundInactive=161,169,177'   \
        'ForegroundLink=0,164,137'         \
        'ForegroundNegative=218,68,83'     \
        'ForegroundNeutral=246,116,0'      \
        'ForegroundNormal=252,252,252'     \
        'ForegroundPositive=39,174,96'     \
        'ForegroundVisited=155,89,182'     \
        ''                                 \
        '[Colors:Header]'                  \
        'BackgroundAlternate=42,46,50'     \
        'BackgroundNormal=49,54,59'        \
        'DecorationFocus=0,164,137'        \
        'DecorationHover=0,164,137'        \
        'ForegroundActive=0,164,137'       \
        'ForegroundInactive=161,169,177'   \
        'ForegroundLink=0,164,137'         \
        'ForegroundNegative=218,68,83'     \
        'ForegroundNeutral=246,116,0'      \
        'ForegroundNormal=252,252,252'     \
        'ForegroundPositive=39,174,96'     \
        'ForegroundVisited=155,89,182'     \
        ''                                 \
        '[Colors:Header][Inactive]'        \
        'BackgroundAlternate=49,54,59'     \
        'BackgroundNormal=42,46,50'        \
        'DecorationFocus=61,174,233'       \
        'DecorationHover=61,174,233'       \
        'ForegroundActive=61,174,233'      \
        'ForegroundInactive=161,169,177'   \
        'ForegroundLink=29,153,243'        \
        'ForegroundNegative=218,68,83'     \
        'ForegroundNeutral=246,116,0'      \
        'ForegroundNormal=252,252,252'     \
        'ForegroundPositive=39,174,96'     \
        'ForegroundVisited=155,89,182'     \
        ''                                 \
        '[Colors:Selection]'               \
        'BackgroundAlternate=8,123,105'    \
        'BackgroundNormal=8,123,105'       \
        'DecorationFocus=0,164,137'        \
        'DecorationHover=0,164,137'        \
        'ForegroundActive=0,164,137'       \
        'ForegroundInactive=255,255,255'   \
        'ForegroundLink=0,164,137'         \
        'ForegroundNegative=176,55,69'     \
        'ForegroundNeutral=198,92,0'       \
        'ForegroundNormal=255,255,255'     \
        'ForegroundPositive=23,104,57'     \
        'ForegroundVisited=155,89,182'     \
        ''                                 \
        '[Colors:Tooltip]'                 \
        'BackgroundAlternate=42,46,50'     \
        'BackgroundNormal=49,54,59'        \
        'DecorationFocus=0,164,137'        \
        'DecorationHover=0,164,137'        \
        'ForegroundActive=0,164,137'       \
        'ForegroundInactive=161,169,177'   \
        'ForegroundLink=0,164,137'         \
        'ForegroundNegative=218,68,83'     \
        'ForegroundNeutral=246,116,0'      \
        'ForegroundNormal=252,252,252'     \
        'ForegroundPositive=39,174,96'     \
        'ForegroundVisited=155,89,182'     \
        ''                                 \
        '[Colors:View]'                    \
        'BackgroundAlternate=35,38,41'     \
        'BackgroundNormal=27,30,32'        \
        'DecorationFocus=0,164,137'        \
        'DecorationHover=0,164,137'        \
        'ForegroundActive=0,164,137'       \
        'ForegroundInactive=161,169,177'   \
        'ForegroundLink=0,164,137'         \
        'ForegroundNegative=218,68,83'     \
        'ForegroundNeutral=246,116,0'      \
        'ForegroundNormal=252,252,252'     \
        'ForegroundPositive=39,174,96'     \
        'ForegroundVisited=155,89,182'     \
        ''                                 \
        '[Colors:Window]'                  \
        'BackgroundAlternate=49,54,59'     \
        'BackgroundNormal=42,46,50'        \
        'DecorationFocus=0,164,137'        \
        'DecorationHover=0,164,137'        \
        'ForegroundActive=0,164,137'       \
        'ForegroundInactive=161,169,177'   \
        'ForegroundLink=0,164,137'         \
        'ForegroundNegative=218,68,83'     \
        'ForegroundNeutral=246,116,0'      \
        'ForegroundNormal=252,252,252'     \
        'ForegroundPositive=39,174,96'     \
        'ForegroundVisited=155,89,182'     \
        ''                                 \
        '[General]'                        \
        'ColorScheme=ChameleonBreezeDark'  \
        'Name=Chameleon Breeze Dark'       \
        ''                                 \
        '[Icons]'                          \
        'Theme=Tela-dark'                  \
        ''                                 \
        '[WM]'                             \
        'activeBackground=49,54,59'        \
        'activeBlend=252,252,252'          \
        'activeForeground=252,252,252'     \
        'inactiveBackground=42,46,50'      \
        'inactiveBlend=161,169,177'        \
        'inactiveForeground=161,169,177'
}

criar_esquema_chameleon_breeze_darker(){
    printf '%s\n'                            \
        '[ColorEffects:Disabled]'            \
        'Color=112,111,110'                  \
        'ColorAmount=0'                      \
        'ColorEffect=0'                      \
        'ContrastAmount=0.65'                \
        'ContrastEffect=1'                   \
        'IntensityAmount=0.1'                \
        'IntensityEffect=2'                  \
        ''                                   \
        '[ColorEffects:Inactive]'            \
        'ChangeSelectionColor=true'          \
        'Color=112,111,110'                  \
        'ColorAmount=-0.9500000000000001'    \
        'ColorEffect=0'                      \
        'ContrastAmount=0.1'                 \
        'ContrastEffect=0'                   \
        'Enable=false'                       \
        'IntensityAmount=0'                  \
        'IntensityEffect=0'                  \
        ''                                   \
        '[Colors:Button]'                    \
        'BackgroundAlternate=20,25,31'       \
        'BackgroundNormal=20,25,31'          \
        'DecorationFocus=0,76,90'            \
        'DecorationHover=0,164,137'          \
        'ForegroundActive=222,222,222'       \
        'ForegroundInactive=190,207,210'     \
        'ForegroundLink=0,170,127'           \
        'ForegroundNegative=255,85,127'      \
        'ForegroundNeutral=0,129,149'        \
        'ForegroundNormal=252,252,252'       \
        'ForegroundPositive=0,164,137'       \
        'ForegroundVisited=127,140,141'      \
        ''                                   \
        '[Colors:Complementary]'             \
        'BackgroundAlternate=20,25,31'       \
        'BackgroundNormal=22,27,34'          \
        'DecorationFocus=0,76,90'            \
        'DecorationHover=44,120,107'         \
        'ForegroundActive=214,214,214'       \
        'ForegroundInactive=163,183,188'     \
        'ForegroundLink=44,120,107'          \
        'ForegroundNegative=255,85,127'      \
        'ForegroundNeutral=255,255,127'      \
        'ForegroundPositive=61,174,233'      \
        'ForegroundVisited=61,174,233'       \
        ''                                   \
        '[Colors:Selection]'                 \
        'BackgroundAlternate=20,25,31'       \
        'BackgroundNormal=0,164,137'         \
        'DecorationFocus=0,76,90'            \
        'DecorationHover=0,164,137'          \
        'ForegroundActive=190,207,210'       \
        'ForegroundInactive=60,174,230'      \
        'ForegroundLink=0,170,127'           \
        'ForegroundNegative=255,85,127'      \
        'ForegroundNeutral=0,129,149'        \
        'ForegroundNormal=252,252,252'       \
        'ForegroundPositive=0,164,137'       \
        'ForegroundVisited=191,210,211'      \
        ''                                   \
        '[Colors:Tooltip]'                   \
        'BackgroundAlternate=20,25,31'       \
        'BackgroundNormal=25,32,40'          \
        'DecorationFocus=0,76,90'            \
        'DecorationHover=0,164,137'          \
        'ForegroundActive=249,183,183'       \
        'ForegroundInactive=190,207,210'     \
        'ForegroundLink=0,170,127'           \
        'ForegroundNegative=255,85,127'      \
        'ForegroundNeutral=0,129,149'        \
        'ForegroundNormal=190,207,210'       \
        'ForegroundPositive=0,164,137'       \
        'ForegroundVisited=127,140,141'      \
        ''                                   \
        '[Colors:View]'                      \
        'BackgroundAlternate=20,25,31'       \
        'BackgroundNormal=20,25,31'          \
        'DecorationFocus=0,76,90'            \
        'DecorationHover=0,164,137'          \
        'ForegroundActive=222,222,222'       \
        'ForegroundInactive=137,153,158'     \
        'ForegroundLink=0,170,127'           \
        'ForegroundNegative=255,85,127'      \
        'ForegroundNeutral=0,129,149'        \
        'ForegroundNormal=252,252,252'       \
        'ForegroundPositive=0,164,137'       \
        'ForegroundVisited=127,140,141'      \
        ''                                   \
        '[Colors:Window]'                    \
        'BackgroundAlternate=20,25,31'       \
        'BackgroundNormal=20,25,31'          \
        'DecorationFocus=0,76,90'            \
        'DecorationHover=0,164,137'          \
        'ForegroundActive=207,207,207'       \
        'ForegroundInactive=190,207,210'     \
        'ForegroundLink=0,170,127'           \
        'ForegroundNegative=255,85,127'      \
        'ForegroundNeutral=0,129,149'        \
        'ForegroundNormal=252,252,252'       \
        'ForegroundPositive=0,164,137'       \
        'ForegroundVisited=127,140,141'      \
        ''                                   \
        '[General]'                          \
        'ColorScheme=ChameleonBreezeDarker'  \
        'Name=Chameleon Breeze Darker'       \
        'TitlebarIsAccentColored=true'       \
        'shadeSortColumn=true'               \
        ''                                   \
        '[KDE]'                              \
        'contrast=4'                         \
        ''                                   \
        '[WM]'                               \
        'activeBackground=20,25,31'          \
        'activeBlend=20,25,31'               \
        'activeForeground=190,207,210'       \
        'inactiveBackground=20,25,31'        \
        'inactiveBlend=20,25,31'             \
        'inactiveForeground=127,140,141'
}

### Instalando o tema Chameleon Breeze Dark ###
echo -e "\nInstalando o tema Chameleon Breeze Dark\n"
wget -q --show-progress https://github.com/jpmsb/preparando-computador-para-engenharia-de-tele/raw/main/compactados/Chameleon-Breeze-Dark.tar.xz -O /tmp/Chameleon-Breeze-Dark.tar.xz

tar -xf /tmp/Chameleon-Breeze-Dark.tar.xz -C /usr/share/themes

### Instalando o tema Chameleon Breeze Darker ###
echo -e "\nInstalando o tema Chameleon Breeze Darker\n"
wget -q --show-progress https://github.com/jpmsb/preparando-computador-para-engenharia-de-tele/raw/main/compactados/Chameleon-Breeze-Darker.tar.xz -O /tmp/Chameleon-Breeze-Darker.tar.xz

tar -xf /tmp/Chameleon-Breeze-Darker.tar.xz -C /usr/share/themes

### Criando tema de cores para o Qt5ct ###
echo '[ColorScheme]
active_colors=#ffffffff, #ff31363b, #ff979797, #ff5e5c5b, #ff9f9f9f, #ff4a4947, #ffffffff, #ffffffff, #ffffffff, #ff1b1e20, #ff2a2e32, #ffe7e4e0, #ff00a489, #fff9f9f9, #ff0986d3, #ffa70b06, #ff5c5b5a, #ffffffff, #ff3f3f36, #ffffffff, #80ffffff
disabled_colors=#ff808080, #ff31363b, #ff979797, #ff5e5c5b, #ff9f9f9f, #ff4a4947, #ff808080, #ffffffff, #ff808080, #ff1b1e20, #ff2a2e32, #ffe7e4e0, #ff13181e, #ff808080, #ff0986d3, #ffa70b06, #ff5c5b5a, #ffffffff, #ff3f3f36, #ffffffff, #80ffffff
inactive_colors=#ffffffff, #ff31363b, #ff979797, #ff5e5c5b, #ff9f9f9f, #ff4a4947, #ffffffff, #ffffffff, #ffffffff, #ff1b1e20, #ff2a2e32, #ffe7e4e0, #ff00a489, #fff9f9f9, #ff0986d3, #ffa70b06, #ff5c5b5a, #ffffffff, #ff3f3f36, #ffffffff, #80ffffff' > /usr/share/qt5ct/colors/chameleon-dark.conf

echo '[ColorScheme]
active_colors=#ffffffff, #ff14191f, #ff979797, #ff5e5c5b, #ff9f9f9f, #ff4a4947, #ffffffff, #ffffffff, #ffffffff, #ff14191f, #ff14191f, #ffe7e4e0, #ff00a489, #fff9f9f9, #ff0986d3, #ffa70b06, #ff5c5b5a, #ffffffff, #ff3f3f36, #ffffffff, #80ffffff
disabled_colors=#ff808080, #ff14191f, #ff979797, #ff5e5c5b, #ff9f9f9f, #ff4a4947, #ff808080, #ffffffff, #ff808080, #ff14191f, #ff14191f, #ffe7e4e0, #ff13181e, #ff808080, #ff0986d3, #ffa70b06, #ff5c5b5a, #ffffffff, #ff3f3f36, #ffffffff, #80ffffff
inactive_colors=#ffffffff, #ff14191f, #ff979797, #ff5e5c5b, #ff9f9f9f, #ff4a4947, #ffffffff, #ffffffff, #ffffffff, #ff14191f, #ff14191f, #ffe7e4e0, #ff00a489, #fff9f9f9, #ff0986d3, #ffa70b06, #ff5c5b5a, #ffffffff, #ff3f3f36, #ffffffff, #80ffffff' > /usr/share/qt5ct/colors/chameleon-darker.conf

### Criando esquema de cor Chameleon Breeze Dark ###
criar_esquema_chameleon_breeze_dark > /usr/share/color-schemes/Chameleon-Breeze-Dark.colors

### Criando esquema de cor Chameleon Breeze Darker ###
criar_esquema_chameleon_breeze_darker > /usr/share/color-schemes/Chameleon-Breeze-Darker.colors
